[2022-02-15 22:49:20,204] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-02-15 22:49:20,263] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-02-15 22:49:20,265] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:49:20,267] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 22:49:20,269] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:49:20,341] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): green_csv_to_gcs_job> on 2019-08-02 06:00:00+00:00
[2022-02-15 22:49:20,354] {standard_task_runner.py:52} INFO - Started process 5518 to run task
[2022-02-15 22:49:20,373] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_download_csv', 'green_csv_to_gcs_job', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '769', '--raw', '--subdir', 'DAGS_FOLDER/download_upload_greentaxi_csv.py', '--cfg-path', '/tmp/tmpw2wpzfzp', '--error-file', '/tmp/tmpbv7vof9g']
[2022-02-15 22:49:20,379] {standard_task_runner.py:77} INFO - Job 769: Subtask green_csv_to_gcs_job
[2022-02-15 22:49:20,573] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [running]> on host 29988b24dbed
[2022-02-15 22:49:20,729] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-15 22:49:20,839] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_download_csv
AIRFLOW_CTX_TASK_ID=green_csv_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2022-02-15 22:49:21,076] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_upload_greentaxi_csv.py", line 37, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-08.csv'
[2022-02-15 22:49:21,189] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=green_taxi_download_csv, task_id=green_csv_to_gcs_job, execution_date=20190802T060000, start_date=20220215T224920, end_date=20220215T224921
[2022-02-15 22:49:21,261] {standard_task_runner.py:92} ERROR - Failed to execute job 769 for task green_csv_to_gcs_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_upload_greentaxi_csv.py", line 37, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-08.csv'
[2022-02-15 22:49:21,350] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-15 22:49:21,459] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-15 22:53:31,344] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-02-15 22:53:31,494] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-02-15 22:53:31,497] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:53:31,501] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 22:53:31,502] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:53:31,648] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): green_csv_to_gcs_job> on 2019-08-02 06:00:00+00:00
[2022-02-15 22:53:31,669] {standard_task_runner.py:52} INFO - Started process 5952 to run task
[2022-02-15 22:53:31,711] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_download_csv', 'green_csv_to_gcs_job', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '793', '--raw', '--subdir', 'DAGS_FOLDER/download_upload_greentaxi_csv.py', '--cfg-path', '/tmp/tmpmrwm_1l9', '--error-file', '/tmp/tmp7e39yppo']
[2022-02-15 22:53:31,727] {standard_task_runner.py:77} INFO - Job 793: Subtask green_csv_to_gcs_job
[2022-02-15 22:53:32,093] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-08-02T06:00:00+00:00 [running]> on host 29988b24dbed
[2022-02-15 22:53:32,444] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-15 22:53:32,573] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_download_csv
AIRFLOW_CTX_TASK_ID=green_csv_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2022-02-15 22:53:51,691] {python.py:175} INFO - Done. Returned value was: None
[2022-02-15 22:53:51,865] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=green_taxi_download_csv, task_id=green_csv_to_gcs_job, execution_date=20190802T060000, start_date=20220215T225331, end_date=20220215T225351
[2022-02-15 22:53:52,094] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 22:53:52,346] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
