[2022-02-15 22:47:52,565] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-15 22:47:52,757] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-15 22:47:52,766] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:47:52,768] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 22:47:52,774] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:47:52,919] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): green_csv_to_gcs_job> on 2019-03-02 06:00:00+00:00
[2022-02-15 22:47:52,966] {standard_task_runner.py:52} INFO - Started process 5316 to run task
[2022-02-15 22:47:53,013] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_download_csv', 'green_csv_to_gcs_job', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '753', '--raw', '--subdir', 'DAGS_FOLDER/download_upload_greentaxi_csv.py', '--cfg-path', '/tmp/tmpr68cq1r0', '--error-file', '/tmp/tmpww552c83']
[2022-02-15 22:47:53,024] {standard_task_runner.py:77} INFO - Job 753: Subtask green_csv_to_gcs_job
[2022-02-15 22:47:53,489] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [running]> on host 29988b24dbed
[2022-02-15 22:47:53,771] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-15 22:47:53,861] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_download_csv
AIRFLOW_CTX_TASK_ID=green_csv_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-02-15 22:47:53,988] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_upload_greentaxi_csv.py", line 37, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-03.csv'
[2022-02-15 22:47:54,150] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=green_taxi_download_csv, task_id=green_csv_to_gcs_job, execution_date=20190302T060000, start_date=20220215T224752, end_date=20220215T224754
[2022-02-15 22:47:54,284] {standard_task_runner.py:92} ERROR - Failed to execute job 753 for task green_csv_to_gcs_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_upload_greentaxi_csv.py", line 37, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-03.csv'
[2022-02-15 22:47:54,361] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-15 22:47:54,610] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-15 22:51:34,793] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-15 22:51:34,842] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-15 22:51:34,844] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:51:34,847] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 22:51:34,855] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 22:51:34,915] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): green_csv_to_gcs_job> on 2019-03-02 06:00:00+00:00
[2022-02-15 22:51:34,928] {standard_task_runner.py:52} INFO - Started process 5733 to run task
[2022-02-15 22:51:34,950] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_download_csv', 'green_csv_to_gcs_job', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '780', '--raw', '--subdir', 'DAGS_FOLDER/download_upload_greentaxi_csv.py', '--cfg-path', '/tmp/tmpp35reiz6', '--error-file', '/tmp/tmptudt_hcs']
[2022-02-15 22:51:34,956] {standard_task_runner.py:77} INFO - Job 780: Subtask green_csv_to_gcs_job
[2022-02-15 22:51:35,137] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_download_csv.green_csv_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [running]> on host 29988b24dbed
[2022-02-15 22:51:35,287] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-15 22:51:35,351] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_download_csv
AIRFLOW_CTX_TASK_ID=green_csv_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-02-15 22:51:49,164] {python.py:175} INFO - Done. Returned value was: None
[2022-02-15 22:51:49,257] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=green_taxi_download_csv, task_id=green_csv_to_gcs_job, execution_date=20190302T060000, start_date=20220215T225134, end_date=20220215T225149
[2022-02-15 22:51:49,429] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 22:51:49,716] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
